//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentALanguageTeacher
{
    using System;
    using System.Collections.Generic;
    
    public partial class accountstatu
    {
        public accountstatu()
        {
            this.accounts = new HashSet<account>();
            this.users = new HashSet<user>();
        }
    
        public string account_status { get; set; }
    
        public virtual ICollection<account> accounts { get; set; }
        public virtual ICollection<user> users { get; set; }
    }
}
