//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentALanguageTeacher
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment
    {
        public int payment_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string username { get; set; }
        public Nullable<int> hours { get; set; }
        public Nullable<System.DateTime> transaction_date { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
        public string payer_email { get; set; }
        public string item_name { get; set; }
        public string transaction_id { get; set; }
        public string transaction_status { get; set; }
        public string update_user { get; set; }
    
        public virtual user user { get; set; }
    }
}
