//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentALanguageTeacher
{
    using System;
    using System.Collections.Generic;
    
    public partial class quickregistration
    {
        public int quick_registration_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> languagel_evel { get; set; }
        public Nullable<int> classes { get; set; }
        public string period { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public string specialrequests { get; set; }
        public Nullable<System.DateTime> time_stamp { get; set; }
        public Nullable<int> class_duration { get; set; }
        public string teacher { get; set; }
        public string teacher_skypeid { get; set; }
        public Nullable<System.DateTime> first_class { get; set; }
        public string admin_comments { get; set; }
        public string student_comments { get; set; }
    
        public virtual user user { get; set; }
    }
}
