//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentALanguageTeacher
{
    using System;
    using System.Collections.Generic;
    
    public partial class route_table
    {
        public int route_id { get; set; }
        public string rout_name { get; set; }
        public string rout_url { get; set; }
        public string physical_file { get; set; }
        public Nullable<System.DateTime> time_stamp { get; set; }
    }
}
