//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentALanguageTeacher
{
    using System;
    using System.Collections.Generic;
    
    public partial class wordofday
    {
        public int word_id { get; set; }
        public string spanish_word { get; set; }
        public string part_of_speech { get; set; }
        public string word_group { get; set; }
        public string english_translation { get; set; }
        public string spanish_sentence { get; set; }
        public string english_sentence { get; set; }
    }
}
