//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentALanguageTeacher
{
    using System;
    using System.Collections.Generic;
    
    public partial class zone
    {
        public zone()
        {
            this.timezones = new HashSet<timezone>();
            this.locations = new HashSet<location>();
        }
    
        public int zone_id { get; set; }
        public string country_code_iso2 { get; set; }
        public string zone_name { get; set; }
    
        public virtual country country { get; set; }
        public virtual ICollection<timezone> timezones { get; set; }
        public virtual ICollection<location> locations { get; set; }
    }
}
