//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentALanguageTeacher
{
    using System;
    using System.Collections.Generic;
    
    public partial class contentmarkup
    {
        public int contentmarkup_id { get; set; }
        public Nullable<int> content_id { get; set; }
        public string language { get; set; }
        public string markup { get; set; }
        public string description { get; set; }
        public bool published { get; set; }
        public System.DateTime time_stamp { get; set; }
    
        public virtual content content { get; set; }
        public virtual contentlanguage contentlanguage { get; set; }
    }
}
