//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentALanguageTeacher
{
    using System;
    using System.Collections.Generic;
    
    public partial class location
    {
        public int location_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string line_1 { get; set; }
        public string line_2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string postal_code { get; set; }
        public string country_code_iso2 { get; set; }
        public Nullable<int> zone_id { get; set; }
        public Nullable<System.DateTime> time_stamp { get; set; }
    
        public virtual country country { get; set; }
        public virtual user user { get; set; }
        public virtual zone zone { get; set; }
    }
}
