//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentALanguageTeacher
{
    using System;
    using System.Collections.Generic;
    
    public partial class picture
    {
        public picture()
        {
            this.answers = new HashSet<answer>();
            this.questions = new HashSet<question>();
        }
    
        public int picture_id { get; set; }
        public string url { get; set; }
        public string caption { get; set; }
        public Nullable<int> order { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<System.DateTime> time_stamp { get; set; }
    
        public virtual ICollection<answer> answers { get; set; }
        public virtual user user { get; set; }
        public virtual ICollection<question> questions { get; set; }
    }
}
