//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentALanguageTeacher
{
    using System;
    using System.Collections.Generic;
    
    public partial class questiontype
    {
        public questiontype()
        {
            this.questions = new HashSet<question>();
        }
    
        public int question_type { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<question> questions { get; set; }
    }
}
