//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentALanguageTeacher
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class rentalanguageteacherEntities : DbContext
    {
        public rentalanguageteacherEntities()
            : base("name=rentalanguageteacherEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<accountstatu> accountstatus { get; set; }
        public DbSet<country> countries { get; set; }
        public DbSet<gender> genders { get; set; }
        public DbSet<language> languages { get; set; }
        public DbSet<my_aspnet_applications> my_aspnet_applications { get; set; }
        public DbSet<my_aspnet_membership> my_aspnet_membership { get; set; }
        public DbSet<my_aspnet_profiles> my_aspnet_profiles { get; set; }
        public DbSet<my_aspnet_roles> my_aspnet_roles { get; set; }
        public DbSet<my_aspnet_sessioncleanup> my_aspnet_sessioncleanup { get; set; }
        public DbSet<my_aspnet_sessions> my_aspnet_sessions { get; set; }
        public DbSet<my_aspnet_users> my_aspnet_users { get; set; }
        public DbSet<my_aspnet_usersinroles> my_aspnet_usersinroles { get; set; }
        public DbSet<questioncategory> questioncategories { get; set; }
        public DbSet<questiontype> questiontypes { get; set; }
        public DbSet<timezone> timezones { get; set; }
        public DbSet<weekday> weekdays { get; set; }
        public DbSet<zone> zones { get; set; }
        public DbSet<user> users { get; set; }
        public DbSet<account> accounts { get; set; }
        public DbSet<answer> answers { get; set; }
        public DbSet<location> locations { get; set; }
        public DbSet<picture> pictures { get; set; }
        public DbSet<question> questions { get; set; }
        public DbSet<questionnaire> questionnaires { get; set; }
        public DbSet<quickregistration> quickregistrations { get; set; }
        public DbSet<review> reviews { get; set; }
        public DbSet<student> students { get; set; }
        public DbSet<teacher> teachers { get; set; }
        public DbSet<timeslot> timeslots { get; set; }
        public DbSet<payment> payments { get; set; }
        public DbSet<wordofday> wordofdays { get; set; }
        public DbSet<contentcategory> contentcategories { get; set; }
        public DbSet<route_table> route_table { get; set; }
        public DbSet<contentlanguage> contentlanguages { get; set; }
        public DbSet<content> contents { get; set; }
        public DbSet<contentmarkup> contentmarkups { get; set; }
    }
}
