<%@ Page Title="Terms-of-Service" Language="C#" MasterPageFile="~/MasterPages/RentALanguageTeacher.Master" AutoEventWireup="true" CodeBehind="TermsOfService.aspx.cs" Inherits="RentALanguageTeacher.TermsOfService" %>

<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="server">



</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="cpMainContent" runat="server">

    <div class="ContentSection">
        
        <div class="ContentSectionHeader"><div class="ContentSectionHeaderText"><%: Page.Title %></div></div>
        
        <div class="ContentSectionContent">

            <div class="Content">

                <div class="ContentTitleImage"><a href="/Home"><img src="/Images/LogoBlack.png" class="center" /></a></div>
                
                <div class="ContentTitletext">

                    <p>At Rent a Language Teacher we want to ensure you and your teacher have the best experience possible.  
                        By using Rent a Language Teacher you agree to all of the terms of service below.  Thank you!</p>

                </div>

            </div>

        </div>

    </div>

    <div id="small-print">

    <div class="ContentSection">
        
        <div class="ContentSectionHeader"><div class="ContentSectionHeaderText">Definitions</div></div>
        
        <div class="ContentSectionContent">

            <div class="Content">

                <ol class="round">

                    <li class="one">
                        Terms and Conditions - Terms and Conditions to be accepted by a student or teacher when using Rent a Language Teacher (RALT)'s service
                    </li>

                    <li class="two">
                        RALT - Rent a Language Teacher company
                    </li>

                    <li class="three">
                        Services - Services provided by RALT on rentalanguageteacher.com, primarily connecting students with teachers
                    </li>

                    <li class="four">
                        Student - Person registering and requesting for a teacher with RALT, or using our online/offline content
                    </li>

                    <li class="five">
                        Teacher - Person registered with RALT that provides a teaching service to students
                    </li>

                    <li class="six">
                        Content - Any online/offline content that is generated by RALT, like Spanish units, articles, grammar, and so on
                    </li>

                    <li class="seven">
                        Package - A set of hours (10, 25, 50) or part thereof that is sold to the student. These are the number of hours of lessons that the teacher is required to provide to the student.
                    </li>

                </ol>

            </div>

        </div>

    </div>

    <div class="ContentSection">
        
        <div class="ContentSectionHeader"><div class="ContentSectionHeaderText">Overview</div></div>
        
        <div class="ContentSectionContent">

            <div class="Content">

                RALT is a website that works as a platform to connect students and Teachers. The website allows students to make a request for a teacher. RALT provides a search service that finds a suitable teacher for the student and then setting up a first meeting with a fixed date and time. RALT collects the payment for the online service and distributes it to the teacher. RALT also generates online and offline content that aids with language learning. This content is available on rentalanguageteacher.com, our Facebook and Twitter sites, as well as sent out through emails to students and teachers. 
By using or accessing the site or the services; or paying for someone else to use or access the site or the services, you agree to the terms and conditions set forth below. If you do not agree with these terms and conditions, neither you nor your designee or giftee may access, download, install, or use (as applicable), the site or the services. For the purposes of this agreement, you means a parent or guardian who pays for using the services as well as the student who accesses or uses the services. If you are a parent, guardian, or other person who enables a child to access the services, you agree to be responsible for such child in the case of damages or indemnification that could properly lie against a child, if not for his or her age.


            </div>

        </div>

    </div>

    <div class="ContentSection">
        
        <div class="ContentSectionHeader"><div class="ContentSectionHeaderText">Type of Services</div></div>
        
        <div class="ContentSectionContent">

            <div class="Content">

                <ol class="round">

                    <li class="one">
                        RALT searches for a teacher at the request of a student. On payment by the student, it schedules the first class with a specified time and date for both the student and the teacher via email. It also provides both the student and the teacher with their respective Skype ID information.
                    </li>

                    <li class="two">
                        RALT collects the money from the student on behalf of the teacher. After deducting a commission for every package sold, RALT distributes the remainder of the money to the teacher.
                    </li>

                    <li class="three">
                        RALT generates online and offline content that aids online language learning. This is provided either free or as a paid service.
                    </li>

                </ol> 

            </div>

        </div>

    </div>

    <div class="ContentSection">
        
        <div class="ContentSectionHeader"><div class="ContentSectionHeaderText">Terms and Conditions of Service</div></div>
        
        <div class="ContentSectionContent">

            <div class="Content">

                <ol class="round">

                    <li class="one">
                        In order to use the service, students have to accept the Terms and Conditions set out in this article by registering with RALT on its website.
                    </li>

                    <li class="two">
                        Registering in the service is voluntary and free of charge.
                    </li>

                    <li class="three">
                        Children under the age of 13 cannot register in the service.
                    </li>

                    <li class="four">
                        Children older than 13, but under the age of 18, can register into the Service only when they have a permission of a parent or legal guardian who is at least 18 years old ("Parent"). The Parent needs to create an account ("Account") for the child. In order to create the Account, the Parent must be a registered student on the site so that the child can use that Account and the Parent can monitor that account as well if he or she desires to do so.
                    </li>

                    <li class="five">
                        The agreement is concluded if a student registers himself or herself in the service, having confirmed that he or she learnt and accepted these Terms and Conditions. The student may at any time resign from the services provided on the basis of these Terms and Conditions.
                    </li>

                    <li class="six">
                        RALT has a right to remove or add some new functionalities to the website and service, at any time. 
                    </li>

                    <li class="seven">
                        All hours/packages bought by the student is valid for one year from the date of purchase. Hours not used within the one year period will be forfeited. Exceptions are granted on a case-by-case basis based on the discretion of RALT.
                    </li>

                    <li class="eight">
                        RALT guarantees the attendance of the teacher only on the first package sold. If the student has a private arrangement with the teacher after the first package, RALT will not be liable for the non-attendance of the teacher or other possible problems pertaining to it.
                    </li>

                    <li class="nine">
                        The student is liable to pay for a scheduled lesson even if he/she did not appear for it. Full-refund cancellations should be made 48 hours in advance before the scheduled date and time.
                    </li>

                    <li class="ten">
                        In the case of an emergency resulting in non-appearance o cutting short of a lesson, the student is entitled to recuperate 50% of the number of hours lost. Emergencies are defined as life and death situations involving the student or a relative or a close friend, city/area wide blackouts or power outages, or determined on a case-by-case basis by RALT and the teacher.
                    </li>

                    <li class="eleven">
                        The scheduled lesson starts at the scheduled time or whenever the teacher arrives, even if the student is late. i.e. If the scheduled time for a one hour lesson is 8am and the student arrives at 8.15am, the lesson will still end at 9am, at the scheduled end time. Students should try to log on to Skype at least 10 minutes before the scheduled time.
                    </li>

                    <li class="twelve">
                        There will be no refunds on packages sold. If the student is unhappy with an assigned teacher, RALT will provide the student with another teacher with no additional charge. If the student is unable to continue with the lessons for personal reasons, the student may transfer the hours to someone else, or request for an extension of the validity of the lessons. The extension will be approved on a case-to-case basis based on RALT's discretion.
                    </li>

                </ol>

            </div>

        </div>

    </div>

    <div class="ContentSection">
        
        <div class="ContentSectionHeader"><div class="ContentSectionHeaderText">Privacy</div></div>
        
        <div class="ContentSectionContent">

            <div class="Content">

                <ol class="round">

                    <li class="one">
                        The full text of RALT's privacy policy is located at: <a href="/Privacy-Policy"> Privacy-Policy</a>
                    </li>

                    <li class="two">
                        By using rentalanguageteacher.com, the student consents to receiving electronic communications from RALT. These communications will include notices about student's account (e.g., shipping and receiving e-mails and other transactional information) and information concerning or related to our service, such as featured content or other announcements
                    </li>

                    <li class="three">
                       User can at any time review and request changes of his or her personal data – via User Profile or by contacting RALT
                    </li>

                </ol>

            </div>

        </div>

    </div>

    <div class="ContentSection">
        
        <div class="ContentSectionHeader"><div class="ContentSectionHeaderText">Trademarks, copyrights and publishing rules</div></div>
        
        <div class="ContentSectionContent">

            <div class="Content">

                <ol class="round">

                    <li class="one">
                        The trademarks, service marks, and logos used and displayed on the RALT website or in any Company Content are registered and unregistered Trademarks of us and others and are protected, without limitation, pursuant to U.S. and foreign trademark laws. You may not use the Trademarks, either ours or others, in any way without the prior written permission of the applicable Trademark owner.
                    </li>

                    <li class="two">
                        At the moment of submitting or displaying any material (including text, audio, video, pictures, graphics, sound clips, and other works of authorship) on the Site, the student and teacher represents and warrants that: 
                        <br />
                        <ul>
                          <li>
                              he/she owns all rights in his/her material (or that he/she has acquired all necessary rights in the material from the actual owner) to enable him/her to grant to us the rights to such material;
                          </li>
                            <li>
                                he/she has paid and will pay in full all fees and other financial obligations (if any) arising from the posting of his/her material;
                            </li>  
                            <li>
                                his/her material is not defamatory in nature, and does not infringe the intellectual property, privacy, publicity or any other legal or moral rights of any third party.
                            </li>
                        </ul> 
                    </li>

                    <li class="three">
                        The student is solely responsible for the content which he or she publishes in the Service. The content published in the Service is protected by intellectual property rights.
                    </li>

                    <li class="four">
                        4.	The company can delete any content published by the student, if in solely judgment of RALT that this content violates the Terms of Services and Conditions or is illegal.
                    </li>

                    <li class="five">
                        5.	Excluding rights to content published by students and teachers, RALT owns exclusive rights to the RALT Service's content, which is protected by the intellectual property rights.
                    </li>

                </ol>

            </div>

        </div>

    </div>

    <div class="ContentSection">
        
        <div class="ContentSectionHeader"><div class="ContentSectionHeaderText">Principles of Using the Service</div></div>
        
        <div class="ContentSectionContent">

            <div class="Content">

                <ol class="round">

                    <li class="one">
                        Each student is obliged to use the offered services in a way compliant with the law, the Terms and Conditions of Service, Terms of Service of a given service, as well as with the principles of social conduct and good practices. A student is particularly obliged: not to carry out any actions hampering the use of the Service, not to carry out any actions infringing privacy of other students, including using the data of other persons as his or her own personal data, as well as to not to place, collect, process and supply other data commonly regarded as indecent, as well as any content infringing the law or personal or property rights of other persons.
                    </li>

                    <li class="two">
                        Using the Service and individual services is free of charge, unless the Terms and Conditions of Service or the Terms of Service of individual services state otherwise. A student is not entitled to put forward any claims against the Company due to introducing charges for using the Service or individual services, as well as due to a presumptive resignation from the charges; a student is especially not entitled to claim any money paid by him or her or to put forward a compensation claim for any damages incurred due to introducing charges for using the Service.
                    </li>

                    <li class="three">
                        A student or teacher must not send via the Service any advertising or promotion correspondence which was not ordered (spam), as well as must not use the Service to put forward and receive social offers.
                    </li>

                    <li class="four">
                        RALT is not liable for the material of private messages sent by the Users via the Service or using the emails provided by RALT.
                    </li>

                    <li class="five">
                        In case of not obeying the principles of these Terms and Conditions of Service, the Company is entitled to block or terminate a student's account without stating the reason. We also reserve the right to take any of the following actions if a student violates any of these Terms: 
                        <br />
                        <ul>
                          <li>
                              stop any purchase transaction
                          </li>
                            <li>
                                prevent or limit access to the Site
                            </li>  
                            <li>
                                and/or remove any prohibited content.
                            </li>
                        </ul> 
                    </li>

                    <li class="six">
                        RALT is not responsible for verifying the identity, qualifications, credentials, biographic information, licensure, and/or any other information regarding any of the students or teachers.
                    </li>

                    <li class="seven">
                        Students are responsible for selecting and accepting the right tutor for their needs.
                    </li>

                    <li class="eight">
                        RALT does not control the quality, relevance or accuracy of any lesson service provided by a teacher, and RALT does not determine whether any teacher is qualified to provide any specific advice.
                    </li>

                </ol>

            </div>

        </div>

    </div>

    <div class="ContentSection">
        
        <div class="ContentSectionHeader"><div class="ContentSectionHeaderText">Prohibited Content and Prohibited Conduct</div></div>
        
        <div class="ContentSectionContent">

            <div class="Content">

                To ensure that RALT is only used and accessed for educational purposes, a student agrees not to engage in (or attempt to engage in) any “Prohibited Conduct,” which includes the following:

                <ol class="round">

                    <li class="one">
                        engage in Tutor/Student communications that are unrelated to learning or the subject of the relevant Lesson, including without limitation communications that solicit or disclose personally identifiable information such as full name, age and city of residence;
                    </li>

                    <li class="two">
                        access or use the Service in any way that is harmful, in violation of these Terms, or in any way that is not in full compliance with any applicable local, state, national or international law, regulation, or statute (including export laws);
                    </li>

                    <li class="three">
                        hack into, access, tamper with, or use services or areas of the Site that he/she is not authorized to access;
                    </li>

                    <li class="four">
                        alter, tamper, damage, or delete any information (such as postings, registration information, profiles, submissions or other communications) in the Service that he/she does not own;
                    </li>

                    <li class="five">
                        use any robot, spider, scraper or other automated means or interface not provided by us to access the Service, to extract data or to gather or use information (such as email addresses) available from the Service in order to transmit unsolicited advertising, “junk mail,” “spam,” “chain letters” or “pyramid schemes”;
                    </li>

                    <li class="six">
                        send to or otherwise impact the Service (or anything or anyone else) with harmful, illegal, deceptive or disruptive code such as a virus, “spyware,” “adware” or other code that could adversely impact the Service or any recipient;
                    </li>

                    <li class="seven">
                        interfere with another student's transaction, disrupt the normal flow of communication, or otherwise act in a manner that negatively affects other students' ability to access or use the Service or to engage in real-time exchanges or transactions; and
                    </li>

                    <li class="eight">
                        collect or store personal information about other students or teachers without their permission, or stalk or harass other students or teachers in any way.
                    </li>

                </ol>

            </div>

        </div>

    </div>

    <div class="ContentSection">
        
        <div class="ContentSectionHeader"><div class="ContentSectionHeaderText">Disclaimer and Indemnification</div></div>
        
        <div class="ContentSectionContent">

            <div class="Content">

                <ol class="round">

                    <li class="one">
                        To the fullest extent permissible pursuant to applicable law, the materials on this Site are provided "as is" and without warranties of any kind either expressed or implied and RALT does not provide any warranty of the item whatsoever, whether express, implied, or statutory, including, but not limited to, any warranty of merchantability or fitness for a particular purpose or any warranty that the contents of the item will be error-free. 
                    </li>

                    <li class="two">
                        RALT does not warrant or make any representations regarding the use or the results of the use of the materials on this Site in terms of their correctness, accuracy, reliability, or otherwise. 
                    </li>

                    <li class="three">
                        The information and descriptions contained herein are not necessarily intended to be complete descriptions of all terms, exclusions and conditions applicable to the products and services, but are provided solely for general informational purposes. 
                    </li>

                    <li class="four">
                        We may provide links to other third-party websites and services (for example, Facebook, Twitter, LinkedIn) which are outside our control and not covered by this Terms of Service. We encourage you to review the privacy statements posted on those websites (and all websites) you visit.
                    </li>

                    <li class="five">
                        Users agree to indemnify and release RALT from any liability regarding loss, claim, damages and expenses arising from any connection to Service content or any third party linked Websites, content or software.
                    </li>

                </ol>

            </div>

        </div>

    </div>

    <div class="ContentSection">
        
        <div class="ContentSectionHeader"><div class="ContentSectionHeaderText">Stipulations</div></div>
        
        <div class="ContentSectionContent">

            <div class="Content">

                <ol class="round">

                    <li class="one">
                        RALT is not a party to or participant of any legal obligations or relationships set up by the students using the Service.
                    </li>

                    <li class="two">
                        RALT reserves the right to: change the principles of using the Service or its individual services, remove or modify the contents and functions of the Service or its individual services, prevent a student or teacher the access to the Service or its individual services without the necessity to justify the reason for such a change.
                    </li>

                    <li class="three">
                        In case of maintenance works RALT is entitled to temporarily suspend functioning of the Service or its individual services.
                    </li>

                    <li class="four">
                        The RALT reserves the right to fully suspend the Service's activities. If it happens, a student or teacher is not entitled to put forward any claims against RALT connected with losing his or her data placed in the Service.
                    </li>

                    <li class="five">
                        A student and teacher uses the Service and services provided by RALT exclusively at his or her own risk.
                    </li>

                    <li class="six">
                        RALT is not liable for lack of implementation or improper implementation of the obligations arising from these Terms and Conditions of Service, if such lack of implementation or improper implementation of the obligations results from circumstances beyond RALT's control despite maintaining due diligence (Force Majeure).
                    </li>

                    <li class="seven">
                        RALT is not liable for potential settlements between the students and teachers, created in the result of using the Service or its individual services, nor is it liable for potential settlements with tax bodies appropriate for the students or teachers, arising from cooperation between the students or teachers. The Company is not liable for any damages and losses incurred by the students or teachers, particularly arising from cooperation between the students or teachers within the Service.
                    </li>

                    <li class="eight">
                        We have the right, but not the obligation, to monitor any activity and content associated with this Service.
                    </li>

                    <li class="nine">
                        RALT reserves the right to report any activity that is suspects violates any law or regulation to appropriate law enforcement officials, regulators, or other governmental officials. To protect our systems and students we may access and disclose any information we consider necessary or appropriate to appropriate law enforcement officials, regulators, or other governmental officials. We reserve the right, at our sole discretion, to pursue a civil lawsuit or criminal prosecution for any alleged or actual illegal activities involving our Service.
                    </li>

                </ol>

            </div>

        </div>

    </div>

    <div class="ContentSection">
        
        <div class="ContentSectionHeader"><div class="ContentSectionHeaderText">Limitation of liability</div></div>
        
        <div class="ContentSectionContent">

            <div class="Content">

                Under no circumstances will RALT or any party involved in the creation, production and delivery of the Site, be liable for damages arising from students' and teachers’ access, use or misuse of the Website or any linked third party site be it direct, incidental, or indirect. Likewise, under no circumstance will RALT or any party involved in the creation, production and delivery of the Site, be liable for system performance, error, interruption, delay or transmission of viruses.

            </div>

        </div>

    </div>

    <div class="ContentSection">
        
        <div class="ContentSectionHeader"><div class="ContentSectionHeaderText">Complaints</div></div>
        
        <div class="ContentSectionContent">

            <div class="Content">

                <ol class="round">

                    <li class="one">
                        RALT enables the Users to table complaints by electronic means and for this purpose provides the email address: <a href="mailto:info@rentalanguageteacher.com">info@rentalanguageteacher.com</a>
                    </li>

                    <li class="two">
                        The subject matter of a complaint is implementing a service by RALT in the way infringing the terms and conditions specified in the service's Terms and Conditions of Service.
                    </li>

                    <li class="three">
                        A complaint must not be based on: 
                                                <br />
                        <ul>
                          <li>
                              Referring to the circumstances connected with improper functioning of the Internet search engine or telecommunication lines
                          </li>
                            <li>
                                Infringing the Terms of Service' terms by a student
                            </li>  
                            <li>
                                Other circumstances connected with the activities taken by entities for whose actions the Company is not liable.
                            </li>
                        </ul> 
                    </li>

                    <li class="four">
                        A complaint should specify the student and briefly describe the reservations tabled.
                    </li>

                    <li class="five">
                       If a complaint needs to be completed, the RALT asks to provide the details about the service implemented.
                    </li>

                </ol>

            </div>

        </div>

    </div>

    <div class="ContentSection">
        
    <div class="ContentSectionHeader"><div class="ContentSectionHeaderText">Final Provisions</div></div>
        
        <div class="ContentSectionContent">

            <div class="Content">

                <ol class="round">

                    <li class="one">
                        The Terms and Conditions of Service specify the principles of using the RALT service made available on www.rentalanguageteacher.com
                    </li>

                    <li class="two">
                        The necessary condition of using the Service and individual services is to learn and accept the Terms and Conditions of Service specified above.
                    </li>

                    <li class="three">
                        The Terms and Conditions of Service is a document passed by the RALT whose powers also include changing them any time. The Terms and Conditions of Service are changed by making new Terms and Conditions of Service available on the Service's website. The most current version of these Terms and Conditions of service can be reviewed by clicking on the "Terms and Conditions of Service" located at the bottom of the pages www.rentalanguageteacher.com. The most current version of the Terms and Conditions of Service will supersede all previous versions. The Terms and Conditions of Service come into force after 5 days from making them available in the Service.
                    </li>

                    <li class="four">
                        A student or teacher is entitled to object to the changes in the Terms and Conditions of Service within 5 days from making the changed Terms and Conditions of Service available in the Service, provided that lack of objection within the aforementioned time limit is understood as accepting them with the effect on the day when they come into force. A student or teacher sends an objection to the following email address: <a href="mailto:info@rentalanguageteacher.com">info@rentalanguageteacher.com</a>
                    </li>

                    <li class="five">
                        A student's objection is equal to his or her terminating the agreement on services, provided that it does not affect mutual obligations of the students and teachers as concerns using the Service.
                    </li>

                    <li class="six">
                        By registering in the Service a student or teacher confirms that he or she learnt the content of these Terms and Conditions of Service and accepts their terms.
                    </li>

                </ol>

            </div>

        </div>

    </div>

        </div>

</asp:Content>
