//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentALanguageTeacher
{
    using System;
    using System.Collections.Generic;
    
    public partial class questionnaire
    {
        public int test_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> question_id { get; set; }
        public Nullable<int> answer_id { get; set; }
        public Nullable<System.DateTime> time_stamp { get; set; }
    
        public virtual answer answer { get; set; }
        public virtual question question { get; set; }
        public virtual user user { get; set; }
    }
}
