//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentALanguageTeacher
{
    using System;
    using System.Collections.Generic;
    
    public partial class answer
    {
        public answer()
        {
            this.questionnaires = new HashSet<questionnaire>();
        }
    
        public int answer_id { get; set; }
        public Nullable<int> question_id { get; set; }
        public string text_english { get; set; }
        public string text_spanish { get; set; }
        public Nullable<int> order { get; set; }
        public Nullable<int> picture_id { get; set; }
        public Nullable<System.DateTime> time_stamp { get; set; }
    
        public virtual picture picture { get; set; }
        public virtual question question { get; set; }
        public virtual ICollection<questionnaire> questionnaires { get; set; }
    }
}
